### ISSUE TITLE
Problém with start plugin

### ISSUE THREAD

**Issue by JamesGNR** [luc-ass/homebridge-evohome#128]
Hello,
I have a problem with plugin. When I started plugin on my Hombridge(Hoobs) I see in log this error:

20. 9. 2022 18:13:47  Evohome BridgeEvohomeLogging into Evohome...
20. 9. 2022 18:13:47 Evohome BridgeEvohomeERRORError during login:
 Error: getaddrinfo EAI_AGAIN tccna.honeywell.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'tccna.honeywell.com'

Can you help me?
Jakub

**Comment by luc-ass** [comment]
Looks like your dns can not find `tccna.honeywell.com`. Are what DNS are you using?

**Comment by JamesGNR** [comment]
Hello,
I have PC connected on the same network and I can connect to tccna.honeywell.com <http://tccna.honeywell.com/>. I tried ping and ping work correctly. Resolve address to IP address. My Internet provider is Starlink. 
I connect to Hoobs over shh and test ping. Ping didn’t find and resolve address tccna.honeywell.com <http://tccna.honeywell.com/>. 
What can I do?
Jakub

**Comment by luc-ass** [comment]
Good, seems like we found the problem. Can you change the underlying DNS to `1.1.1.1` or `9.9.9.9`?

**Comment by luc-ass** [comment]
have you encountered this problem again?

**Comment by JamesGNR** [comment]
Hello,I thought that I responded to your email. I solved my problem with the HOOBS support team. They recommended me and I followed these steps:https://support.hoobs.org/topics/connectivity/plugin-site-unavailableRegards. Jakub7. 10. 2022 v 11:01, Lucas Gasenzer ***@***.***>:﻿
have you encountered this problem again?

**Comment by luc-ass** [comment]
Thanks for your feedback.

**Comment by JamesGNR** [comment]
Hello,
Everything works. HOOBS support send me this

https://support.hoobs.org/topics/connectivity/plugin-site-unavailable￼
Thank you for your support.
Jakub

**Comment by JamesGNR** [comment]
Hello,
I did not changed anything. I deleted resolve.conf in my HOOBS and rebooted. Problem was in Linux.
This is HOOBS support descriptions:


A recent Linux system update caused some DNS issues affecting HOOBS Box users running on model HSLF-1 as well as DIY installs on Raspberry Pi boards.
If you are not able to install plugins or your plugins fail to connect to the internet after a System update, and your logs read "Plugin site unavailable",
this likely affects you. To fix the issue, you need to remove the resolv.conf file and reboot your system using the following terminal command:

How to access the Terminal

sudo rm /etc/resolv.conf; sudo reboot
Input your terminal password at the prompt and press enter. Your password will not show as you type it in the terminal.

**Comment by luc-ass** [comment]
Thank you for documenting this here to help other people in the future!

**Comment by JamesGNR** [comment]
You are welcome :-)
