### ISSUE TITLE
Mode is always switching to Off (on 0.9.x version)

### ISSUE THREAD

**Issue by tomsteenbakkers** [luc-ass/homebridge-evohome#132]
Hi
I seem to be having a problem with the mode options. Especially with the 0.9.x version of the plugin.

The thermostat is always showing off. Pressing any of "Heat", "Cool" or "Auto" shows the set temperature changing but then after a few seconds it goes back to being "Off".

I revert back to version 0.8.8 and then the behavior is normal and the Mode option is working.

I already remove the Evohome bridge and also clear the cache but this is not solving the issue when the 0.9.x version is installed.

**Comment by luc-ass** [comment]
This was a feature implemented by @KarlJGray [here](https://github.com/luc-ass/homebridge-evohome/pull/126). TBH, I was sceptical whether it would be clearer or even confusing. Seems it is confusing to you. 

In the background the thermostat will not turn off. It will just be represented as off, when the set temperature is below the measured room temperature.

As a test you could set the temperature much higher than room temperature and have a look at the mode. Please report back. We might revert these changes or add a configuration option if it is confusing to most people.

Cheers

**Comment by tomsteenbakkers** [comment]
Hi Luc,

Just did the test. If you set the temperature higher than the current value, it turn on.

I find this confusing. Now, it looks like the Mode option if not working.

I like to suggestion to add a config option for this ‘feature’

Cheers

Tom

On 24 Nov 2022, at 08:18, Lucas Gasenzer ***@***.***> wrote:

﻿

This was a feature implemented by @KarlJGray<https://github.com/KarlJGray> here<https://github.com/luc-ass/homebridge-evohome/pull/126>. TBH, I was sceptical whether it would be clearer or even confusing. Seems it is confusing to you.

In the background the thermostat will not turn off. It will just be represented as off, when the set temperature is below the measured room temperature.

As a test you could set the temperature much higher than room temperature and have a look at the mode. Please report back. We might revert these changes or add a configuration option if it is confusing to most people.

Cheers

**Comment by luc-ass** [comment]
Thank you for your feedback! Should be relatively easy to implement. I'll let you know, when this is available.

**Comment by tomsteenbakkers** [comment]
Thanks, If if need to do some testing please let me know






On 28 Nov 2022, at 09:34, Lucas Gasenzer ***@***.***> wrote:



Thank you for your feedback! Should be relatively easy to implement. I'll let you know, when this is available.

**Comment by luc-ass** [comment]
This should be fixed as of [v0.10.1](https://github.com/luc-ass/homebridge-evohome/releases/tag/v0.10.1)

Don't hesitate to reopen this issue, if you encounter problems!

**Comment by tomsteenbakkers** [comment]
Works like a charm! Excellent work! #happy-user
