### ISSUE TITLE
temperatureAboveAsOff not working

### ISSUE THREAD

**Issue by MaestroCollin** [luc-ass/homebridge-evohome#139]
I have set this option to on but the thermostat doesn't turn to off in homekit

**Comment by luc-ass** [comment]
Did you find a fix?

**Comment by MaestroCollin** [comment]
Kinda, i found out that it is the current heatingCooling state instead of the target one. 

However, I still can't use it in an automation.. any idea why?

**Comment by luc-ass** [comment]
From what I can see, the state can not be used as a trigger. Neither Home.app nor Eve.app give an option to do that.

**Comment by MaestroCollin** [comment]
In controller.app you can use it as a trigger for automations. In eve.app too, but it's named to valve, the value can be either open or closed.

**Comment by luc-ass** [comment]
The valve value actually reflects the valve position. It isn't changed by this plugin. Could you describe your use case? Perhaps we can find something useful to change in the plug-in ;)

**Comment by MaestroCollin** [comment]
If the target temperature is below the current temperature I want to trigger an automation for my heating panel connected to an smart plug.

**Comment by MaestroCollin** [comment]
Is it maybe possible to add some kind of switch or toggle exposed to HomeKit?

**Comment by georgesdib** [comment]
My PR #143 adds the valve position to be exactly that, valve is closed if temperature is below and vice versa. You could then use that as a trigger.

**Comment by 5xPa** [comment]
I would be more than happy to test. But I am unsure what's required

**Comment by luc-ass** [comment]
Simply update the plugin in Homebridge. It has been released today.

**Comment by 5xPa** [comment]
I have already updated and 
Switched the hot water On from Homekit. 
Off from  Evohome App. 
Switched On from app 
Switched Off from  Homekit
I thought your were requesting %valve position

**Comment by georgesdib** [comment]
> I have already updated and
> Switched the hot water On from Homekit.
> Off from Evohome App.
> Switched On from app
> Switched Off from Homekit
> I thought your were requesting %valve position

If you check the valve position in the Eve app, when the target temperature is above current temperature it should show the valve to be open and vice versa. It’s 100% or 0% binary.

**Comment by SeaneyC** [comment]
Seems to be working for me, awesome, thanks!!

**Comment by 5xPa** [comment]
I have never used the Eve app to look at radiator Thermostats. Was surprised when it shows a graph of temperatures . For each room except the Living room! didn't know this was available. As tend to use only HomeKit app
I don't see anything showing % valve position

**Comment by georgesdib** [comment]
> I have never used the Eve app to look at radiator Thermostats. Was surprised when it shows a graph of temperatures . For each room except the Living room! didn't know this was available. As tend to use only HomeKit app
> I don't see anything showing % valve position

You may need to enable but clicking on Edit on top right and enable valve

**Comment by 5xPa** [comment]
Thanks that was what was required
