### ISSUE TITLE
Second location not show in Home app

### ISSUE THREAD

**Issue by SanderBaron** [luc-ass/homebridge-evohome#144]
very happy with this plugin, works perfect!
In my home I have two EvoHome systems (cause EvoHome is stupid..) and installed this as two separate locations, (downstairs, upstairs). I changed 'Location Index' to 1, but still only one location is showing up. Both locations are showing up in the EvoHome app and I can manage them normally. Do I need to do more rather than changing location index? Thanks!

**Comment by luc-ass** [comment]
That's an interesting edge case you have there. I've never thought about using two instances inside the same home... No idea what actually happens in the background. Which of your locations shows up in your home (0, 1, etc?).

**Comment by SanderBaron** [comment]
Yep, I'm also not happy with it, but this is because Honeywell doesn't take its job serious... 

I've set the Location Index to 1 and I'm seeing the second location in the Home app...

Maybe this is something to add for a future update because I think it will happen more and more because of the energy transition where people have and old fashioned heater and a heatpump that both need to be controlled.

Hope you can help out, not in a hurry and I'm very much willing to test a beta. 

Thanks!

**Comment by georgesdib** [comment]
I actually have the same setup and it works perfectly well. I have the 2 setup as their own sub bridge, and you just add the 2 sub bridge to your home and it works.
Do you not run it as a sub bridge? I never tried it in this configuration. But it’s better as a sub-bridge anyway.

**Comment by SanderBaron** [comment]
Thanks Georges! I'm kinda new to this game, what do you mean with a sub-bridge? I'm running Hoobs on a Mac Mini and I have this plugin installed as a bridge.

**Comment by georgesdib** [comment]
> Thanks Georges! I'm kinda new to this game, what do you mean with a sub-bridge? I'm running Hoobs on a Mac Mini and I have this plugin installed as a bridge.

Oh, I am not familiar with HOOBS, I use homebridge, in homebridge you have the option to run each plugin as a sub-bridge, HOOBS must have the same functionality. The main advantage is that if the plugin is slow, it does not slow down the whole of homebridge, and also you can separately kill and restart the plugin without having to restart the whole of homebridge.

For the evohome plugin, you can run each location as its own sub-bridge (and not just the plugin, it essentially runs it as if it's 2 separate plugins which happen to have the same code). I don't know how that work in HOOBS.

This is the wiki page that explains it for homebridge:

https://github.com/homebridge/homebridge/wiki/Child-Bridges

**Comment by SanderBaron** [comment]
> > Thanks Georges! I'm kinda new to this game, what do you mean with a sub-bridge? I'm running Hoobs on a Mac Mini and I have this plugin installed as a bridge.
> 
> Oh, I am not familiar with HOOBS, I use homebridge, in homebridge you have the option to run each plugin as a sub-bridge, HOOBS must have the same functionality. The main advantage is that if the plugin is slow, it does not slow down the whole of homebridge, and also you can separately kill and restart the plugin without having to restart the whole of homebridge.
> 
> For the evohome plugin, you can run each location as its own sub-bridge (and not just the plugin, it essentially runs it as if it's 2 separate plugins which happen to have the same code). I don't know how that work in HOOBS.
> 
> This is the wiki page that explains it for homebridge:
> 
> https://github.com/homebridge/homebridge/wiki/Child-Bridges
> 
> Edit: a quick search would suggest that HOOBS has the same functionality: https://support.hoobs.org/docs/60e0c685646faaa152f10dd8

Thanks for your help! I just found it out myself! Basically just like you've mentioned, install the plugin as a new bridge and it's up and running! I'm very happy!

**Comment by luc-ass** [comment]
Glad you got it to work!
