### ISSUE TITLE
departing

### ISSUE THREAD

**Issue by luc-ass** [luc-ass/homebridge-evohome#17]
Hello people,

I start this thread to let you know maintenance of this plugin will be minimal in the future. I will soon move to a new home having underfloor heating and I will not be able to take my evohome with me. I might pick this up in the future but for the time being i sincerely hope, that manufacturers get their heads around HomeKit faster than I expect.

If there is someone out there who wants to take care about this plugin, I will be grateful to transfer the plugin or give admin access. I will be happy to assist if anything can be solved by me.

Regards, Lucas

**Comment by luc-ass** [comment]
Well, looks like I will continue using Evohome after all. So - nothing to change here -

**Comment by brownad** [comment]
👍
