### ISSUE TITLE
Quick actions

### ISSUE THREAD

**Issue by thorpeado** [luc-ass/homebridge-evohome#18]
Hi
I've just set up a raspberry pi running home bridge and added your plugin. Thanks for all the hard work, it's working great. Just wondered if you have got anywhere with implementing support for quick actions?

**Comment by luc-ass** [comment]
Not yet, no. Want to help out? I was planing on making quick actions a separate device but it will be a long time before I can spend some time with this plugin again...

**Comment by plangin** [comment]
Hi,
idea / feature request as workaround:
Turning off heating in Evohome does actually set the thermostats to 5° C. The lowest value in HomeKit seems to be 10° C.
So instead of ignoring the HomeKit command to turn off heating, could you please set the corresponding evohome thermostat to 5° C?
Thanks

**Comment by luc-ass** [comment]
I can certainly have a look into it. Just need to figure out how to „cancel override“ in evohome first.

**Comment by fredericvl** [comment]
I've added a pull request with the support for quick actions (as seperate switch devices in homekit)

**Comment by luc-ass** [comment]
Wow! This plugin is goin places ;)

I’ll merge and publish as soon as I can test it. Thank you so much for your contributions!!

**Comment by luc-ass** [comment]
Okay, I installed your request from https://github.com/fredericvl/homebrdige-evohome.git and everything seems to work. I'll merge and publish today. Can you please look at "Eco Mode"? The plugin initialized with "Eco Mode" on while it was really off. After changing it back and forth it was still working the way it is supposed to.

**Comment by luc-ass** [comment]
it has been published to npm (v0.3.0)

**Comment by luc-ass** [comment]
Guess I was a little to fast - changes have been reverted to the last version. Reasons:

1. Is-Temperature is no longer reflected: always gives back 5 °C
2. Temperature change until next switchPoint no longer working. (Erased by overlapping pull-requests).

**Comment by luc-ass** [comment]
Solved

**Comment by thorpeado** [comment]
Hi,
Thanks for your work in implementing this.
One other thing, would you be able to add a switch to reset the system to 'Auto' mode? I've tried to have a look myself but such a noob and can't get it to work :(
