### ISSUE TITLE
setTemperature doesn't pass the temperature value

### ISSUE THREAD

**Issue by luc-ass** [luc-ass/homebridge-evohome#4]
Hey @zizzex,

just saw, that the plugin doesn't cause a problem when setting the temperature (the base station even reflects that the phone changed something - which is then persistent) but the temperature is not changed. Have you noticed something similar?

**Comment by zizzex** [comment]
Nop, I haven't noticed.
I have tested by setting a new temperature through Siri and then checking in the Evohome App on my iPhone and everything seemed correct.
There could be some issues related to the server datetime. Right now, it tries to understand the timezone and adds 10 minutes, so if the time on the server is not correct or the timezone calculation is wrong, it could tell the Honeywell webservice to set the new temperature untill a date/time in the past.

**Comment by luc-ass** [comment]
Good idea. I'll check. Perhaps we can change it to "until next change"

**Comment by luc-ass** [comment]
Okay, I updated the system time of my raspi (productive system) and rebooted. Now it works perfectly! Thanks again!

Next up: Change 10 minutes to "until next change"
