### ISSUE TITLE
No colors in HomeKit app

### ISSUE THREAD

**Issue by tomsteenbakkers** [luc-ass/homebridge-evohome#41]
When I look at other thermostat (i.e. Tado) I notice that the tiles are using colors. This plugin works but the tile is always gray and the temperature is not showing any color. 

Any idea how I can use these colors in this plugin?

**Comment by slippyr4** [comment]
Tile colors aren't for aesthetics, they mean different things. Grey means off; Red is heat, blue cool, green satisfied etc.
Currently homebridge-evohome reports status incorrectly to HomeKit and the colours are therefore wrong.

**Comment by luc-ass** [comment]
This has been solved from v0.5.1 onwards.
