### ISSUE TITLE
One hour difference when setting temperature

### ISSUE THREAD

**Issue by jankeesvw** [luc-ass/homebridge-evohome#48]
First of all, thanks for this great homebridge plugin 🙏.

I have a timing issue, I think this is related to #20, when I set the temperature from homekit I see this in my logs:

> ![image](https://user-images.githubusercontent.com/167882/51035815-8ff06c80-15ab-11e9-9e99-f0a510c2d40b.png)

As you can see it is scheduled until 17:00 which is correct, but when I open my honeywell app on my iPhone I see that it's actually scheduled until 18:00. I live in the Netherlands (CEST).

> ![image](https://user-images.githubusercontent.com/167882/51035880-c3cb9200-15ab-11e9-8ebb-ce5e3d4f893f.png)

Anyone knows how to fix this?

**Comment by luc-ass** [comment]
Have you set the system time on your Homebridge device? Mine was set to GMT and that caused errors of the like.

**Comment by jankeesvw** [comment]
Thanks for the hint, I'm running it in Docker on my Synology NAS and I just found out that there is [a ENV variable ](https://github.com/oznu/docker-homebridge#parameters)to set the timezone. It was running in `Europe/london`.

I just changed it to `Europe/Amsterdam` and now it's setting the time correctly. Thanks for the reply @luc-ass.

**Comment by luc-ass** [comment]
Glad I was able to help.
