### ISSUE TITLE
System Mode is false - Evohome Failed "an error has occurred"

### ISSUE THREAD

**Issue by runeix** [luc-ass/homebridge-evohome#50]
Hi there, 

I've been trying to get the evohome plugin running and i've come across a couple of issues. 

I'll start with the good bit, which is that the plugin loads up, finds my device and then finds the correct current temperature of the thermostat.

Here's where i start having a problem. 
In homekit 5 accessories are created as switches for the modes (Away, Custom, Heating Off, Day Off, Auto with Eco) but no thermostat accessory is created. 

The logs are saying : "system mode away is false" , which is then repeated for the other 4 options. 
if you try and press one of the switches in home kit i get: " Evohome failed: message "an error has occured" 

any idea's where it's failing? 

I'm running: 
homebridge version 0.4.49 on a Raspberry Pi 3B+ 
version 0.6.1 of the evohome plugin
Thermostat model: RTH9580WF1005GG
Software Rev: 03.02.00.00
Config Rev: 04.00
Radio Rev: 05.02.07.10
Date Code:1323

Homebridge Config (syntax correct on RPi):
Platform: evohome 
Name: Heater
Username :xxxxxxxx
Password: xxxxxxxxx
TemperatureUnit" Celsius
LocationIndex: 0 

I'm based in Australia with the correct date and time on both the RPi and the thermostat.
Control via the honeywell Home app works correctly.

**Comment by runeix** [comment]
No Worries, 

I've just been using the TCC app in the meantime.

The model is the one linked below.  its natural gas powered central heating with only 1 temp/thermostat for the entire house.

https://www.honeywellhome.com/en/products/thermostat/wi-fi-smart-thermostat-rth9580

**Comment by luc-ass** [comment]
Have you tried https://github.com/NorthernMan54/homebridge-tcc ? 
It is supposed to work with your device.

**Comment by runeix** [comment]
I’ve tried homebridge-tcc but it’s only developed for the US website whereas your evohome plugin works for the international site which I have to use to get my device to work in Australia
