### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by paskovitch** [luc-ass/homebridge-evohome#51]
Why is it that the accessory in the home application shows the temperature only 26 degrees? In reality, there are 27 degrees in the room and the evohome app shows this well.

**Comment by luc-ass** [comment]
Can you be a bit more specific? Is it a device that you are not aware of? Could it be the controller itself?

**Comment by paskovitch** [comment]
In the homekit application, the temperature is shown up to 26 degrees by the thermostat supplement. Honeywell Home app normally displays over 26 degrees.

**Comment by luc-ass** [comment]
Ah, so all the devices are working properly, only the temperature caps at 26 °C? This is probably a hard coded limit. I'll have a look.

**Comment by luc-ass** [comment]
Got it. index.js lins 642 states that the read temperature maxes out at the maximum setable temperature. Probably due to copy paste during creation of this plugin.

You could change that value to something else (i.e. 50 or so) and then test it. If it works I would be most happy to implement it in the live version.

**Comment by paskovitch** [comment]
It works, thank you!

**Comment by luc-ass** [comment]
Great. Can you provide me wit the exact line that is working? I’ll change it in the repo and upload the fix to NPM.

**Comment by paskovitch** [comment]
.setProps({
                    minValue: 1,
                    maxValue: 50,
                    minStep: this.device.valueResolution
                  });

**Comment by luc-ass** [comment]
Thanks. I’ll update it in the coming days.

**Comment by luc-ass** [comment]
Okay. It's now published on NPM. Thanks for your input!
