### ISSUE TITLE
Honeywell Home Support

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [luc-ass/homebridge-evohome#52]
Hey,

Just wondering if you could make this plugin to work with honeywell home(lyric) thermostats. I don’t know how to code that well, and I know that Honeywell has a website for their Honeywell Home api (https://developer.honeywell.com/). Just wondering if you could make this support their other thermostats too?

**Comment by luc-ass** [comment]
This plug-in was developed extremely specific to the evohome system. I guess if there’s anyway to add compatibility for the lyric system it would have to be separate plug-in.
