### ISSUE TITLE
Window open support

### ISSUE THREAD

**Issue by rooi** [luc-ass/homebridge-evohome#53]
Hi,

Have you thought of an implementation of window open support? I believe it is not in the api, but perhaps one can simulate the same behavior by switching the heating on/off.

I tried this approach but while switching the heating off seems to work (target temperature to 5 instead of 15), switching it back on does not seems to work properly. When trying to switch it on in the homekit app, the temperature is set to 15 and Evohome does not seem to accept this setting and switch back off.

I would expect that switching it back on would resume the schedule, of even more pretty, go back to the latest stage.

Thanks!

Roy

**Comment by luc-ass** [comment]
Just for my understanding: What would be the use of this? I mean the thermostats do regulate this automatically but do this on a fixed time scale. My thermostats go back to normal after approximately 15 minutes regardless wether the windows are still open (one of the major drawbacks in my opinion).

**Comment by rooi** [comment]
Hi,

The open window detection does not work properly in my house (old 17th century building with some draught near the radiator valves).
Recently I’ve automated my windows on the top floor and this, perhaps, allows me to bypass the open window detection. For other windows I may add a homekit sensor to achieve something similar.

Roy

**Comment by luc-ass** [comment]
Hello rooi, I just updated the plugin to v0.7.2. This includes a fix that should enable you to:
* window open → set heating to `off`
* window closed → set heating to `heat`

Would you test it and give some feedback?

**Comment by rooi** [comment]
Thanks @luc-ass!
I did a quick test and it seems to work well. I'll try to do some more testing soon

**Comment by luc-ass** [comment]
Okay, then I’ll close the issue. Don’t hesitate to reopen it if you notice any problems.
