### ISSUE TITLE
[Evohome] Error during Login: invalid_grant

### ISSUE THREAD

**Issue by chris-baden-baden** [luc-ass/homebridge-evohome#58]
Dear developer - I installed latest Version but always get the same error notification:

„[Evohome] Error during Login: invalid_grant“

I don‘t know how to fix this - any ideas?
Thank you so much!

Environment: 
- homebridge-evohome v0.7.2
- Zeitzone | GMT+0200

Raspbian GNU/Linux Buster (10)
raspberrypi
Node v12.16.2
Npm v6.14.4

**Comment by luc-ass** [comment]
the `invalid_grat` refers to wrong credentials. Would you please double check your login credentials, perhaps even test them on the official website: https://getconnected.honeywellhome.com/

**Comment by luc-ass** [comment]
Just some more questions:
* Did your system work before or is this your first install?
* Please check wether your password contains `&`. This is for some reason known to cause errors, as described [here](https://community.home-assistant.io/t/official-honeywell-evohome-round-thermostat-integration-eu-only/59733/524).

**Comment by chris-baden-baden** [comment]
- I tested my credentials on this site: https://getconnected.honeywellhome.com/de/ 
then clicked TCC Germany. They are correct. I can log in and can see and operate my evohome zones…

- The homebridge protocol Shows: 
[Evohome] Error during Login: invalid_grant
Setup Payload:
X-HM://0023ISYWYN7NO

**Comment by chris-baden-baden** [comment]
I'll check, yes the Password contains &. Will change and come back

**Comment by chris-baden-baden** [comment]
NOW IT'S WORKING! WAS THE "&" IN THE PASSWORD!
**THANK YOU LUCAS**

**Comment by luc-ass** [comment]
😄 You are welcome. Sorry for the inconvenience... I'll add this issue to the main page...
