### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by tomsteenbakkers** [luc-ass/homebridge-evohome#59]
Just installed the LTS. I notice that when setting a new temperature the plugin is using the wrong time. 

`[5/3/2020, 9:39:37 AM] [Evohome] The current time is 08:39:37`

Now the plugin is losing track with the schedule. Checked home app and that has the right timezone.

**Comment by luc-ass** [comment]
You are right. Strange behavior. I suspect that this is caused by daylight saving time. I will have a look into it.

**Comment by luc-ass** [comment]
Okay, found it. This behavior is caused because the plugin calculates the `correctTime` based on the time zone stored for your location on the server. This does not respect daylight saving time.

To fix this bug I changed it to the "system time". You can try it by installing the plugin from github. If it works I'll include it in the next release.

**Comment by tomsteenbakkers** [comment]
Ok, will do. 

What is the command to do this?

**Comment by luc-ass** [comment]
This depends on the installation type you have (docker/native/raspberry). In my case, running the native Raspberry Pi image I had to go to terminal on the homebridge interface and enter:
```
cd /usr/local/lib
sudo -E -n npm install git+https://github.com/luc-ass/homebridge-evohome.git
```

**Comment by tomsteenbakkers** [comment]
I have native raspberry with homebridge using heb-services

I will try

Met vriendelijke groet/Kind Regards,

Tom Steenbakkers
T +31 654731716

On 3 May 2020, at 11:07, Lucas Gasenzer <notifications@github.com> wrote:

﻿

This depends on the installation type you have (docker/native/raspberry). In my case, running the native Raspberry Pi image I had to go to terminal on the homebridge interface and enter:

cd /usr/local/lib
sudo -E -n npm install git+https://github.com/luc-ass/homebridge-evohome.git

**Comment by luc-ass** [comment]
Be careful! You posted your telephone number to a public repo 😉

**Comment by tomsteenbakkers** [comment]
Fixed. 🥺

**Comment by luc-ass** [comment]
So the bug is fixed?

**Comment by tomsteenbakkers** [comment]
No, remove my number 🤩 I working on it. Homebridge is in a different location since I did a reinstall using homebridge-config-ui

**Comment by tomsteenbakkers** [comment]
Tested and this solve the issue!

```
[5/3/2020, 11:48:04 AM] [Evohome] Request to set target temperature to 18
[5/3/2020, 11:48:05 AM] [Evohome] The current time is 11:48:05
[5/3/2020, 11:48:05 AM] [Evohome] Schedule points for today (Sunday)
[5/3/2020, 11:48:05 AM] [Evohome] - 09:00:00
[5/3/2020, 11:48:05 AM] [Evohome] - 17:00:00 -> next change
[5/3/2020, 11:48:05 AM] [Evohome] - 23:00:00
[5/3/2020, 11:48:05 AM] [Evohome] Setting target temperature for Woonkamer Thermostat to 18° until 17:00:00
[5/3/2020, 11:48:05 AM] [Evohome] Successfully changed temperature!
```

**Comment by luc-ass** [comment]
Great news. You can keep this version running on your system. An updated will be coming quite soon. Thanks for spotting this issue!

**Comment by tomsteenbakkers** [comment]
Sure, no problem! I will be notify by homebridge-config-ui when the new version arrives.
