### ISSUE TITLE
No Thermostat accessory created 

### ISSUE THREAD

**Issue by runeix** [luc-ass/homebridge-evohome#60]
Hi there, 

I've installed the plugin and it loads up and connects to my account correctly, finding the device and the correct temperature. 

However no accessory tile is created in either Homebridge, the home app or eve. 

The optional switches are still created, although i haven't tried to see if they are functional. 

When i first tried to install there was an error regarding an existing UUID file, which i had to manually delete to get the plugin to install, this file however has been created again when the plugin has installed.  (likely left over from a previous install of this plug in a few years ago).

Thanks,

**Comment by luc-ass** [comment]
Sounds mighty strange....

Have you got the possibility to do a new set up on a different system and check whether the system is working?￼ perhaps on a raspberry pi or a Docker container…￼￼

**Comment by luc-ass** [comment]
Have you tried it with Homebridge v1.1.2? I read something about changes in the cache.

**Comment by runeix** [comment]
I've ended up rebuilding homebridge on a new image with homebridge updated to v.1.1.2 , still the same problem!

I can see that it finds the thermostat in the logs and it's current status, but the plugin isn't creating a thermostat in the home app on my phone or in the UI for homebridge 

`[8/20/2020, 23:34:12] [Evohome] Logged into Evohome!
[8/20/2020, 23:34:13] [Evohome] You have 1 location(s). This instance will be using Index No 0
[8/20/2020, 23:34:13] [Evohome] You have 1 device(s).
[8/20/2020, 23:34:15] [Evohome] 0: THERMOSTAT (20°)`

**Comment by Maykel1969** [comment]
I have the same problem.
There is a correct login and the switches are created. But there is no temperature display or setting possibility.

Any idea??

**Comment by Maykel1969** [comment]
Does anyone know how to fix this? The maker of this plugin is not responding and I do not have the knowledge to fix it myself.
It’s a shame because the plugin is connecting correctly to honeywell so the technical part of the plugin is fine. The only thing missing is the thermostat icon.

HELP! :-)

**Comment by luc-ass** [comment]
Hey there. 

First, the warnings you are experiencing above are no problem. It just tells you that the plugins are no longer maintained and so we should at some time move on to alternatives. 

Second, what kind of thermostat are you using? This plugin was written with only the HR92 in mind.

**Comment by Maykel1969** [comment]
Lucas,
I wasn’t aware that the type of thermostat might be different.
I use a Honeywell Round Connected together with the Evohome gateway. So this is for sure different then your setup. However the login to the Honeywell portal works correctly and the switches on/off and eco really work! Also in the log I see a correct reading of the current room temperature.
So I think you are close to solving this. If I can be of any assistance then just let me know.
Cheers, Maykel

**Comment by luc-ass** [comment]
I think in #39 this problem is close to be solved - so keep an eye on that... I'll close this issue as we are on track 🤗
