### ISSUE TITLE
Temperature does not persist if no schedule exists

### ISSUE THREAD

**Issue by luc-ass** [luc-ass/homebridge-evohome#69]
I’m still investigating but i think that the problem is slightly different.
If I change the setting to 18.0 then after a minute the honywell app jumps back to 21.0 ! At that moment the home and eve app both say that the setpoint is 18.0 ?!?!
For some reason the app automatically jumps back to 21.0 but there is no schedule in the honeywell app anymore.

I do see something strange in the log. Does your plugin send a “until” command without info? Is that the reason that the temperature is only set for 1 minute??
![09093610-764E-4FE4-BA7B-CD0EFFD0A6B1](https://user-images.githubusercontent.com/77012346/105158397-3910bc80-5b0e-11eb-9c9a-eae207a21d92.jpeg)

_Originally posted by @Maykel1969 in https://github.com/luc-ass/homebridge-evohome/issues/39#issuecomment-763485385_

**Comment by Maykel1969** [comment]
It's clear now that the honeywell app jumps back to 21.0 oC after each change of setpoint with homekit.
Changing the setting on the thermostat and in the honeywell app is not a problem.

What is also strange is that the temperature was correctly lowered during the night for which I used an automation at 22.00. I did check this in the eve app.

Is there some kind of hidden schedule that overrules the setting?

**Comment by luc-ass** [comment]
I suspect, that the call for "PermanentOverride" is somehow buggy. As I have no room with such settings, I didn't catch that. I added some additional logging into the beta branch. If you have some time, please install the beta branch and post the logs after requesting a temperature change.
```npm install https://github.com/luc-ass/homebridge-evohome.git#beta```

**Comment by Maykel1969** [comment]
So here you see that it jumps back after 40sec

20-1-2021 13:01:53 [Evohome] Current temperature of Woonkamer Thermostat is 21.5°
20-1-2021 13:01:53 [Evohome] Target temperature for Woonkamer Thermostat is 21.5°
20-1-2021 13:01:55 [Evohome] HEAT or COOL selected, previous state AUTO, HEAT or COOL. Doing nothing.
20-1-2021 13:01:58 [Evohome] Request to set target temperature to 15.5
20-1-2021 13:02:03 [Evohome] The current time is 13:02:03
20-1-2021 13:02:03 [Evohome] Setting target temperature for Woonkamer Thermostat to 15.5° until 
20-1-2021 13:02:03 endtime is:
20-1-2021 13:02:03 [Evohome] Successfully changed temperature!
20-1-2021 13:02:03 [Evohome] { id: 'xxxxxxxxxxx' }
20-1-2021 13:02:44 [Evohome] Updating: Woonkamer currentTempChange from: 21.5 to: 21
20-1-2021 13:02:44 [Evohome] Updating: Woonkamer targetTempChange from: 15.5 to: 21
20-1-2021 13:02:58 [Evohome] Target temperature for Woonkamer Thermostat is 21°
20-1-2021 13:02:58 [Evohome] Current temperature of Woonkamer Thermostat is 21°

**Comment by luc-ass** [comment]
So the plugin doesn't even call for a permanent override. Added some more logging. Please give it another try.
```
npm install https://github.com/luc-ass/homebridge-evohome.git#beta
```

**Comment by Maykel1969** [comment]
20-1-2021 13:28:56 [Evohome] Request to set target temperature to 13.5
20-1-2021 13:28:58 [Evohome] The current time is 13:28:58
20-1-2021 13:28:58 [Evohome] Setting target temperature for Woonkamer Thermostat to 13.5° until 
20-1-2021 13:28:58 endtime is:
20-1-2021 13:28:58 called for temporary override
20-1-2021 13:28:58 [Evohome] Successfully changed temperature!

**Comment by luc-ass** [comment]
Yay, we are on track. I'll make some additional changes and let you know in a few minutes.

**Comment by luc-ass** [comment]
Okay. Let's give it another shot.

**Comment by Maykel1969** [comment]
That seems to be working! The honeywell app now shows that the setting is "permanent".

20-1-2021 14:28:45 [Evohome] Current temperature of Woonkamer Thermostat is 21.5°
20-1-2021 14:28:45 [Evohome] Target temperature for Woonkamer Thermostat is 17.5°
20-1-2021 14:28:48 [Evohome] HEAT or COOL selected, previous state AUTO, HEAT or COOL. Doing nothing.
20-1-2021 14:28:51 [Evohome] Request to set target temperature to 22
20-1-2021 14:28:54 [Evohome] The current time is 14:28:54
20-1-2021 14:28:54 [Evohome] Setting target temperature for Woonkamer Thermostat to 22° until null
20-1-2021 14:28:54 endtime is: null
20-1-2021 14:28:54 called for permanent override
20-1-2021 14:28:54 {"HeatSetpointValue":22,"SetpointMode":"PermanentOverride","TimeUntil":null}
20-1-2021 14:28:55 [Evohome] Successfully changed temperature!

**Comment by luc-ass** [comment]
Thank you so much for your testing. I'll remove the extra logging and push this to the `master`. Keep an eye open for version 0.8.0 😁
