### ISSUE TITLE
Stored hot water support

### ISSUE THREAD

**Issue by djfanatix** [luc-ass/homebridge-evohome#80]
Hi,

Are you planning to implement the hot water module soon?

You can see here some source code:

https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/evohome.markdown

Or the evohome async

https://github.com/zxdavb/evohome-async

Thanks!

**Comment by luc-ass** [comment]
Hey there. What kind of functionality are you expecting from "hot water"? I have no such device, so I have no insight of  how to use it. As we are in the middle of a rewrite of the plugin this might still be somewhat far away but I'll consider it as soon as we get there.

**Comment by djfanatix** [comment]
If it would just show up as a thermostat is fine. I know setting the temperature is not possible, but a read out of the temperature + the on/off functionality would be nice.

**Comment by luc-ass** [comment]
Then perhaps a switch (on/off) + temperature sensor would be best?

**Comment by djfanatix** [comment]
yeah also good

**Comment by SeaneyC** [comment]
+1 for hot water temp viewing and on/off functionality would be great!

**Comment by metaljay** [comment]
+2 also wanting this :)
