### ISSUE TITLE
Honeywell server down and Update how do I install

### ISSUE THREAD

**Issue by 5xPa** [luc-ass/homebridge-evohome#82]
Hi I've only had Hoobs for a week, so at the bottom of learning curve. Installed evohome and working.
This morning gave the following command "set living room to 21 degrees" command appeared to be accepted. 
Check on evohome controller. Room temperature had not updated!
Opened the Honeywell app, couldn't login. It appears the Honeywell server is down. 
Should there be an error if settings are accepted by Honeywell?

Also received an email notification on update. In the readme file command "npm install -g homebridge-evohome@latest"
ran this in hoobs terminal, received various errors. 
How do I install the update?

**Comment by luc-ass** [comment]
This is work in progress. The plugin fails if Honeywell servers respond with an unexpected answer (like during updates). Please try again after the update finished. I will push an update as soon as I manage to throw an exemption during updates. Sorry for the inconvenience.

**Comment by 5xPa** [comment]
Thanks for the reply.
Do you mean a Honeywell Update?
Apologies or so many questions, I have never used Linux or Raspberry Pi 

My system includes a separate hot water tank. I noted you ask for someone to test on system with Hot Water tank

**Comment by luc-ass** [comment]
No, this Plugin needs to be enhanced. Please leave a little message in the "hot water" section. I'll let you know as soon as we are there.
