### ISSUE TITLE
Siri command "Family Room to 21 Degrees" 

### ISSUE THREAD

**Issue by 5xPa** [luc-ass/homebridge-evohome#84]
Hi If I use Siri set Family Room to 21 degrees"
Works Ok but my understanding is Temperature will revert to next scheduled time change on Evohome. 
I have tried few rooms next programmed time change is 22:40, yet looking honeywell app it states "until 05:40"
The hoobs logs are in agreement with local UK time.
Ran Terminal mode enter timedatectl command which returned 
               Local time: Tue 2021-02-23 12:18:17 MST  <<<<<<<<<<<<7 hours out from local time
               Universal time: Tue 2021-02-23 19:18:17 UTC
               RTC time: n/a
                Time zone: America/Denver (MST, -0700)
                System clock synchronized: yes
                NTP service: active
                RTC in local TZ: no

As indicated it's 7 hours out. If I subtract 7 hours from "until 05:40" I would get 22:40, which would be next evohome scheduled time. 
If I am correct and there is a more than reasonable chance I'm incorrect! How do I change the time. Hoobs is reporting the correct time. Yet checking in terminal mode the core is in a different time zone.
How do I change time?

**Comment by 5xPa** [comment]
Solved after much searching 
in terminal mode entered following command

sudo timedatectl set-timezone Europe/London 
timedatectl now returns
               Local time: Tue 2021-02-23 20:24:38 GMT  >>>>>>> was previously out by 7 hours
               Universal time: Tue 2021-02-23 20:24:38 UTC
                 RTC time: n/a
                Time zone: Europe/London (GMT, +0000) >>>>>>previously America/Denver
                System clock synchronized: yes
                NTP service: active
                RTC in local TZ: no

Restart service and Family room 21 degrees 
Honeywell app shows Family Room 21 alarm clock symbol 22:40 in agreement with schedule.

**Comment by luc-ass** [comment]
👍
