### ISSUE TITLE
Installed Thermostats moving to Unassigned! room

### ISSUE THREAD

**Issue by 5xPa** [luc-ass/homebridge-evohome#85]
I have HOOBS running for just over 1 week. 
Plugins installed
Evohome
Texecom (Alarm)
Sonos ZP
Dummy With Accessoryinformation  (dummy switches to create Night or Day)

As beginner been restarting services as I modify the configs. Evohome works great can now use Siri "Living Room Thermostat to 21 Degrees. Works fine. 
Occasionally have found the the Thermostat disappear from the rooms I have allocated. Ending up as Unassigned. Has happened a number of times. 
So I left them in Unassigned and placed them in the required rooms on HomeKit. 

Today noticed that Evohome plugin was not responding. Not even showing thermostats in HOOBS Unassigned, think the service failed. Once restarted service Thermostat showed up in Unassigned, in HomeKit showed in default room.
Do the room Names need to Match Exactly in Homekit and Hoobs?
Do the accessory names need to match for Example on installing the Thermostat in showed as "Living Room Thermostat" and the room was named Living Room. In Homekit I modified the name to "thermostat"

It's probably something dumb on my part. The plugin runs great its just on occasional restart service, get a warning "failed to initialize" 
May be relevant I was creating automations using "Controler for Homekit" 

Any help greatly appreciated.

**Comment by luc-ass** [comment]
No you are not dumb. This is a known bug, as the Thermostats for some reason go back to the default room if the plugin fails (mostly because the Server is unreachable).
