### ISSUE TITLE
Translations support

### ISSUE THREAD

**Issue by JesseRiemens** [luc-ass/homebridge-evohome#86]
Currently, when homekit starts, it will use the English names for all accessories. (Honeywell name + " thermostat" for example.)
Could we parameterize this and add a translations file so these names could be derived from the locale setting of honeywell or homebridge?

- [ ] Decide on locale source
- [ ] Parameterize names
- [ ] Add translations in file

**Comment by luc-ass** [comment]
I'd like this. Did you build anything? This is somewhat related to an issue where I'd like to read the system locale, but haven't had the time to look into it. Any ideas?

**Comment by JesseRiemens** [comment]
I haven't done it, no. However I am willing to translate everything in Dutch. According to [this Reddit post](https://www.reddit.com/r/homebridge/comments/f2xjtd/change_language_of_homebridge_config_ui_x/?utm_source=share&utm_medium=ios_app&utm_name=iossmf), homebridge ui uses the browser language setting for this. But since this is backend, that probably will not work.

**Comment by luc-ass** [comment]
Yeah, that is for the base-UI, but not for the plugins themselves. As I see it this is not supported right now and no other plugin has found a way. Feel free to reopen this, if you find a way. I'd happily support it!
