### ISSUE TITLE
Where do I need an email and password for?

### ISSUE THREAD

**Issue by Yorlinq** [luc-ass/homebridge-evohome#88]
I use my EVOHOME for a few years now but I never had to register and therefor I do not have an account.

Does this mean I can't use this plugin?

**Comment by 5xPa** [comment]
I have used Evohome for a number of years. I have always used Honeywell own App, which requires an account (no charge) this is the login and passwords I use.

**Comment by Yorlinq** [comment]
I have installed the Honeywell home app but when I want to add a new product (the EVOHOME) it's not there. Probably because of country (The Netherlands) limitations.

1) Is this the app you're referring too?
2) What country do you live? So I can try to set it in the app...

**Comment by 5xPa** [comment]
The app on apple store is "Total Connect Comfort Intl"
I live in the UK 

I did a quick search I think this Netherlands site
https://getconnected.honeywellhome.com/nl/honeywell-home-app

**Comment by Maykel1969** [comment]
Works perfectly in the Netherlands with Round connected thermostat.
